package com.niranjan.englisharticle.data.local

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.room.migration.Migration
import androidx.sqlite.db.SupportSQLiteDatabase

@Database(
    entities = [
        MeaningEntity::class,
        RecentArticleEntity::class,
        SavedWordEntity::class
    ],
    version = 5,
    exportSchema = false
)
abstract class EnglishArticleDatabase : RoomDatabase() {
    abstract fun meaningDao(): MeaningDao

    abstract fun recentArticleDao(): RecentArticleDao

    abstract fun savedWordDao(): SavedWordDao

    companion object {
        @Volatile
        private var instance: EnglishArticleDatabase? = null

        private val migration1To2 = object : Migration(1, 2) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL(
                    """
                    CREATE TABLE IF NOT EXISTS saved_words (
                        savedKey TEXT NOT NULL PRIMARY KEY,
                        word TEXT NOT NULL,
                        sentence TEXT NOT NULL,
                        lookupMode TEXT NOT NULL,
                        articleTitle TEXT NOT NULL,
                        meaningKannada TEXT NOT NULL,
                        simpleEnglish TEXT NOT NULL,
                        partOfSpeech TEXT NOT NULL,
                        explanationKannada TEXT NOT NULL,
                        exampleEnglish TEXT NOT NULL,
                        exampleKannada TEXT NOT NULL,
                        savedAtMillis INTEGER NOT NULL,
                        practiceAttempts INTEGER NOT NULL,
                        correctAttempts INTEGER NOT NULL,
                        lastPracticedAtMillis INTEGER
                    )
                    """.trimIndent()
                )
            }
        }

        private val migration2To3 = object : Migration(2, 3) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL(
                    "ALTER TABLE recent_articles ADD COLUMN idiomaticPhrasesJson TEXT NOT NULL DEFAULT '[]'"
                )
            }
        }

        private val migration3To4 = object : Migration(3, 4) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL("ALTER TABLE recent_articles ADD COLUMN summaryWhatHappenedEnglish TEXT NOT NULL DEFAULT ''")
                db.execSQL("ALTER TABLE recent_articles ADD COLUMN summaryWhatHappenedKannada TEXT NOT NULL DEFAULT ''")
                db.execSQL("ALTER TABLE recent_articles ADD COLUMN summaryGistEnglish TEXT NOT NULL DEFAULT ''")
                db.execSQL("ALTER TABLE recent_articles ADD COLUMN summaryGistKannada TEXT NOT NULL DEFAULT ''")
            }
        }

        /**
         * Gives every article a content identity, collapses the duplicates that
         * accumulated without one, and indexes the column history is sorted by.
         *
         * Existing installs are expected to hold duplicates: `saveRecentArticle` was a
         * plain insert against an autogenerated key and ran again on every summary, so
         * opening an article and tapping "Get article context" left two full-body rows.
         * Backfilling and then collapsing repairs that history in place rather than
         * leaving users to live with it.
         */
        private val migration4To5 = object : Migration(4, 5) {
            override fun migrate(db: SupportSQLiteDatabase) {
                db.execSQL(
                    "ALTER TABLE recent_articles ADD COLUMN contentHash TEXT NOT NULL DEFAULT ''"
                )

                // Read fully before writing: updating a table while its own cursor is open
                // is not something SQLite guarantees.
                val rows = mutableListOf<Triple<Long, String, String>>()
                db.query("SELECT id, title, cleanArticle FROM recent_articles").use { cursor ->
                    while (cursor.moveToNext()) {
                        rows += Triple(
                            cursor.getLong(0),
                            cursor.getString(1).orEmpty(),
                            cursor.getString(2).orEmpty()
                        )
                    }
                }
                for ((id, title, cleanArticle) in rows) {
                    db.execSQL(
                        "UPDATE recent_articles SET contentHash = ? WHERE id = ?",
                        arrayOf<Any>(recentArticleContentHash(title, cleanArticle), id)
                    )
                }

                // Collapse duplicates, keeping the highest id per hash. Higher id means
                // inserted later, and the later copy is the enriched one — the duplicate
                // was created by the summary save — so this keeps the richer row.
                db.execSQL(
                    """
                    DELETE FROM recent_articles
                    WHERE id NOT IN (SELECT MAX(id) FROM recent_articles GROUP BY contentHash)
                    """
                )

                // Names must match Room's index_<table>_<column> convention exactly, or the
                // schema validation Room runs after migrating will reject the database.
                db.execSQL(
                    "CREATE UNIQUE INDEX IF NOT EXISTS index_recent_articles_contentHash " +
                        "ON recent_articles (contentHash)"
                )
                db.execSQL(
                    "CREATE INDEX IF NOT EXISTS index_recent_articles_savedAtMillis " +
                        "ON recent_articles (savedAtMillis)"
                )
            }
        }

        fun getInstance(context: Context): EnglishArticleDatabase {
            return instance ?: synchronized(this) {
                instance ?: Room.databaseBuilder(
                    context.applicationContext,
                    EnglishArticleDatabase::class.java,
                    "english_article.db"
                )
                    .addMigrations(migration1To2, migration2To3, migration3To4, migration4To5)
                    .build()
                    .also { instance = it }
            }
        }
    }
}
