package com.niranjan.englisharticle.data

import android.util.Log
import android.util.Xml
import com.niranjan.englisharticle.domain.YouTubeTranscript
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import org.xmlpull.v1.XmlPullParser
import java.io.BufferedReader
import java.io.InputStreamReader
import java.io.OutputStreamWriter
import java.io.StringReader
import java.net.HttpURLConnection
import java.net.URL

/**
 * Fetches transcripts for public YouTube videos using the YouTube watch page +
 * Innertube player endpoint to resolve and download caption tracks.
 */
class YouTubeTranscriptService {

    suspend fun fetchTranscript(rawUrl: String): YouTubeTranscript = withContext(Dispatchers.IO) {
        val trimmedUrl = rawUrl.trim()
        logInfo("fetchTranscript:start url=$trimmedUrl")
        try {
            val videoId = extractVideoId(trimmedUrl)
                ?: error("Could not find a YouTube video ID in this link.")
            logDebug("fetchTranscript:videoId=$videoId")

            val playerData = fetchPlayerData(videoId)
            val title = playerData
                .optJSONObject("videoDetails")
                ?.optString("title")
                ?.takeIf { it.isNotBlank() }
                .orEmpty()
            val author = playerData
                .optJSONObject("videoDetails")
                ?.optString("author")
                ?.takeIf { it.isNotBlank() }
                .orEmpty()

            val tracksJson = extractCaptionTracks(playerData, videoId)
            logInfo("fetchTranscript:captionTracks=${tracksJson.length()}")
            if (tracksJson.length() == 0) {
                error("This video does not have any captions or transcript available.")
            }

            val track = pickPreferredTrack(tracksJson)
                ?: error("This video does not have a transcript we can read.")
            val languageCode = track.optString("languageCode").takeIf { it.isNotBlank() }.orEmpty()
            val isAutoGenerated = track.optString("kind") == "asr"
            logInfo("fetchTranscript:selectedTrack language=$languageCode autoGenerated=$isAutoGenerated")

            val transcriptUrl = track.optString("baseUrl")
                .takeIf { it.isNotBlank() }
                ?.replace("&fmt=srv3", "")
                ?.let(::normalizeTranscriptUrl)
                ?: error("YouTube returned an empty transcript URL.")
            logDebug("fetchTranscript:transcriptEndpoint=${summarizeUrl(transcriptUrl)}")

            val transcriptXml = httpGet(transcriptUrl)
            val transcript = parseTranscriptXml(transcriptXml)
            if (transcript.isBlank()) {
                error("YouTube returned an empty transcript for this video.")
            }

            val transcriptWordCount = transcript.split(Regex("\\s+")).count { it.isNotBlank() }
            logInfo(
                "fetchTranscript:success videoId=$videoId titleLength=${title.length} words=$transcriptWordCount"
            )

            YouTubeTranscript(
                videoId = videoId,
                title = title,
                author = author,
                languageCode = languageCode,
                isAutoGenerated = isAutoGenerated,
                transcript = transcript
            )
        } catch (error: Throwable) {
            logError("fetchTranscript:failed url=$trimmedUrl reason=${error.message}", error)
            throw error
        }
    }

    private fun fetchPlayerData(videoId: String): JSONObject {
        val watchHtml = fetchVideoHtml(videoId)
        val apiKey = extractInnertubeApiKey(watchHtml, videoId)
        return fetchInnertubeData(videoId, apiKey)
    }

    private fun extractCaptionTracks(playerData: JSONObject, videoId: String): JSONArray {
        assertPlayability(playerData, videoId)
        return playerData
            .optJSONObject("captions")
            ?.optJSONObject("playerCaptionsTracklistRenderer")
            ?.optJSONArray("captionTracks")
            ?: error("Subtitles are disabled for this video.")
    }

    private fun pickPreferredTrack(tracks: JSONArray): JSONObject? {
        val list = (0 until tracks.length()).map { tracks.getJSONObject(it) }
        val englishManual = list.firstOrNull {
            it.optString("languageCode").startsWith("en", ignoreCase = true) &&
                it.optString("kind") != "asr"
        }
        if (englishManual != null) return englishManual

        val englishAuto = list.firstOrNull {
            it.optString("languageCode").startsWith("en", ignoreCase = true)
        }
        if (englishAuto != null) return englishAuto

        return list.firstOrNull()
    }

    private fun fetchVideoHtml(videoId: String): String {
        logDebug("fetchVideoHtml:start videoId=$videoId")
        var html = fetchHtml(videoId)
        if (html.contains(CONSENT_FORM_MARKER)) {
            logInfo("fetchVideoHtml:consent page detected; attempting cookie flow")
            val consentCookie = createConsentCookie(html)
                ?: error("Failed to automatically provide YouTube consent cookie.")
            html = fetchHtml(videoId, consentCookie)
            if (html.contains(CONSENT_FORM_MARKER)) {
                error("Failed to automatically provide YouTube consent cookie.")
            }
        }
        logDebug("fetchVideoHtml:received bytes=${html.length}")
        return html
    }

    private fun fetchHtml(videoId: String, consentCookie: String? = null): String {
        return httpGet("$WATCH_URL?v=$videoId", consentCookie = consentCookie)
    }

    private fun createConsentCookie(html: String): String? {
        val match = CONSENT_VALUE_PATTERN.find(html) ?: return null
        return "YES+" + match.groupValues[1]
    }

    private fun extractInnertubeApiKey(html: String, videoId: String): String {
        val match = INNERTUBE_API_KEY_PATTERN.find(html)
        if (match != null && match.groupValues.size > 1) {
            logDebug("extractInnertubeApiKey:found keyLength=${match.groupValues[1].length} videoId=$videoId")
            return match.groupValues[1]
        }
        if (html.contains(RECAPTCHA_MARKER)) {
            error("YouTube is blocking requests from this network. Please try a different network.")
        }
        error("Could not parse YouTube page data for this video.")
    }

    private fun fetchInnertubeData(videoId: String, apiKey: String): JSONObject {
        logDebug("fetchInnertubeData:start videoId=$videoId")
        val requestBody = JSONObject()
            .put("context", INNERTUBE_CONTEXT)
            .put("videoId", videoId)
        val raw = httpPostJson(
            INNERTUBE_API_URL.replace("{api_key}", apiKey),
            requestBody.toString()
        )
        val result = JSONObject(raw)
        val status = result.optJSONObject("playabilityStatus")?.optString("status").orEmpty()
        logDebug("fetchInnertubeData:done videoId=$videoId playabilityStatus=$status")
        return result
    }

    private fun assertPlayability(playerData: JSONObject, videoId: String) {
        val playability = playerData.optJSONObject("playabilityStatus") ?: return
        val status = playability.optString("status")
        if (status.isBlank() || status == PLAYABILITY_OK) return

        val reason = playability.optString("reason")
        logWarn("assertPlayability:status=$status reason=$reason videoId=$videoId")
        if (status == PLAYABILITY_LOGIN_REQUIRED) {
            if (reason == PLAYABILITY_REASON_BOT_DETECTED) {
                error("YouTube is blocking requests from this network. Please try a different network.")
            }
            if (reason == PLAYABILITY_REASON_AGE_RESTRICTED) {
                error("This video is age-restricted and cannot be transcribed without sign-in.")
            }
        }
        if (status == PLAYABILITY_ERROR && reason == PLAYABILITY_REASON_VIDEO_UNAVAILABLE) {
            if (videoId.startsWith("http://") || videoId.startsWith("https://")) {
                error("Invalid video ID. Please paste a YouTube video link or ID.")
            }
            error("This video is unavailable.")
        }

        val subReasons = playability
            .optJSONObject("errorScreen")
            ?.optJSONObject("playerErrorMessageRenderer")
            ?.optJSONObject("subreason")
            ?.optJSONArray("runs")
        val detailText = if (subReasons == null || subReasons.length() == 0) {
            ""
        } else {
            (0 until subReasons.length())
                .mapNotNull { index ->
                    subReasons.optJSONObject(index)?.optString("text")?.takeIf { it.isNotBlank() }
                }
                .joinToString(" | ")
        }
        if (reason.isNotBlank() && detailText.isNotBlank()) {
            error("YouTube cannot play this video: $reason ($detailText)")
        }
        if (reason.isNotBlank()) {
            error("YouTube cannot play this video: $reason")
        }
        error("YouTube cannot play this video.")
    }

    private fun httpGet(urlString: String, consentCookie: String? = null): String {
        return httpRequest(
            urlString = urlString,
            method = "GET",
            consentCookie = consentCookie
        )
    }

    private fun httpPostJson(urlString: String, jsonBody: String): String {
        return httpRequest(
            urlString = urlString,
            method = "POST",
            body = jsonBody,
            contentType = "application/json"
        )
    }

    private fun httpRequest(
        urlString: String,
        method: String,
        body: String? = null,
        contentType: String? = null,
        consentCookie: String? = null
    ): String {
        val connection = (URL(urlString).openConnection() as HttpURLConnection).apply {
            requestMethod = method
            connectTimeout = 15_000
            readTimeout = 20_000
            instanceFollowRedirects = true
            setRequestProperty("User-Agent", USER_AGENT)
            setRequestProperty("Accept-Language", "en-US")
            if (!consentCookie.isNullOrBlank()) {
                setRequestProperty("Cookie", "CONSENT=$consentCookie")
            }
            if (!contentType.isNullOrBlank()) {
                setRequestProperty("Content-Type", contentType)
            }
            if (body != null) {
                doOutput = true
            }
        }
        try {
            if (body != null) {
                OutputStreamWriter(connection.outputStream, Charsets.UTF_8).use { writer ->
                    writer.write(body)
                }
            }
            val code = connection.responseCode
            val stream = if (code in 200..299) connection.inputStream else connection.errorStream
            val body = stream?.let {
                BufferedReader(InputStreamReader(it, Charsets.UTF_8)).use { reader -> reader.readText() }
            }.orEmpty()
            if (code == 429) {
                logWarn("httpRequest:429 method=$method endpoint=${summarizeUrl(urlString)}")
                error("YouTube is blocking requests from this network (HTTP 429).")
            }
            if (code !in 200..299) {
                logWarn(
                    "httpRequest:failed method=$method code=$code endpoint=${summarizeUrl(urlString)} body=${preview(body)}"
                )
                error("YouTube request failed (HTTP $code).")
            }
            return body
        } finally {
            connection.disconnect()
        }
    }

    private fun parseTranscriptXml(xml: String): String {
        val parser = Xml.newPullParser()
        parser.setFeature(XmlPullParser.FEATURE_PROCESS_NAMESPACES, false)
        parser.setInput(StringReader(xml))

        val builder = StringBuilder()
        var event = parser.eventType
        var inText = false
        while (event != XmlPullParser.END_DOCUMENT) {
            when (event) {
                XmlPullParser.START_TAG -> if (parser.name == "text") inText = true
                XmlPullParser.TEXT -> if (inText) {
                    val piece = HTML_TAGS.replace(decodeEntities(parser.text), "").trim()
                    if (piece.isNotEmpty()) {
                        if (builder.isNotEmpty()) builder.append(' ')
                        builder.append(piece)
                    }
                }
                XmlPullParser.END_TAG -> if (parser.name == "text") inText = false
            }
            event = parser.next()
        }
        return builder.toString()
    }

    /**
     * The transcript text is double-escaped: outer XML wraps content like
     * `&amp;#39;` which decodes to `&#39;` and then `'`.
     */
    private fun decodeEntities(text: String): String {
        var decoded = text
            .replace("&amp;", "&")
            .replace("&lt;", "<")
            .replace("&gt;", ">")
            .replace("&quot;", "\"")
            .replace("&apos;", "'")
        decoded = NUMERIC_ENTITY.replace(decoded) { match ->
            val raw = match.groupValues[1]
            val codePoint = if (raw.startsWith("x", ignoreCase = true)) {
                raw.drop(1).toIntOrNull(16)
            } else {
                raw.toIntOrNull()
            }
            codePoint?.let {
                runCatching { String(Character.toChars(it)) }.getOrNull()
            } ?: match.value
        }
        return decoded
    }

    private fun summarizeUrl(urlString: String): String {
        return runCatching {
            val parsed = URL(urlString)
            val safePath = parsed.path.ifBlank { "/" }
            "${parsed.protocol}://${parsed.host}$safePath"
        }.getOrElse { urlString.take(120) }
    }

    private fun preview(text: String, maxLength: Int = 180): String {
        return text.replace(Regex("\\s+"), " ").take(maxLength)
    }

    private fun logDebug(message: String) = logInternal(level = "D", message = message)

    private fun logInfo(message: String) = logInternal(level = "I", message = message)

    private fun logWarn(message: String) = logInternal(level = "W", message = message)

    private fun logError(message: String, error: Throwable) = logInternal(level = "E", message = message, error = error)

    private fun logInternal(level: String, message: String, error: Throwable? = null) {
        val logged = runCatching {
            when (level) {
                "D" -> if (error == null) Log.d(TAG, message) else Log.d(TAG, message, error)
                "I" -> if (error == null) Log.i(TAG, message) else Log.i(TAG, message, error)
                "W" -> if (error == null) Log.w(TAG, message) else Log.w(TAG, message, error)
                else -> if (error == null) Log.e(TAG, message) else Log.e(TAG, message, error)
            }
            true
        }.getOrDefault(false)
        if (!logged) {
            println("[$TAG][$level] $message")
            error?.printStackTrace()
        }
    }

    companion object {
        private const val TAG = "YouTubeTranscriptSvc"
        private const val WATCH_URL = "https://www.youtube.com/watch"
        private const val YOUTUBE_BASE_URL = "https://www.youtube.com"
        private const val INNERTUBE_API_URL = "https://www.youtube.com/youtubei/v1/player?key={api_key}"
        private const val USER_AGENT =
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 " +
                "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
        private const val CONSENT_FORM_MARKER = "action=\"https://consent.youtube.com/s\""
        private const val RECAPTCHA_MARKER = "class=\"g-recaptcha\""
        private const val PLAYABILITY_OK = "OK"
        private const val PLAYABILITY_ERROR = "ERROR"
        private const val PLAYABILITY_LOGIN_REQUIRED = "LOGIN_REQUIRED"
        private const val PLAYABILITY_REASON_BOT_DETECTED = "Sign in to confirm you're not a bot"
        private const val PLAYABILITY_REASON_AGE_RESTRICTED = "This video may be inappropriate for some users."
        private const val PLAYABILITY_REASON_VIDEO_UNAVAILABLE = "This video is unavailable"
        private val INNERTUBE_CONTEXT = JSONObject(
            """{"client":{"clientName":"ANDROID","clientVersion":"20.10.38"}}"""
        )
        private val INNERTUBE_API_KEY_PATTERN =
            Regex("\"INNERTUBE_API_KEY\":\\s*\"([a-zA-Z0-9_-]+)\"")
        private val CONSENT_VALUE_PATTERN = Regex("""name="v"\s+value="(.*?)"""")
        private val HTML_TAGS = Regex("""<[^>]*>""", RegexOption.IGNORE_CASE)
        private val NUMERIC_ENTITY = Regex("&#(x?[0-9A-Fa-f]+);")

        /**
         * Accepts the common YouTube link shapes:
         *   - https://www.youtube.com/watch?v=VIDEO_ID
         *   - https://m.youtube.com/watch?v=VIDEO_ID
         *   - https://youtu.be/VIDEO_ID
         *   - https://www.youtube.com/shorts/VIDEO_ID
         *   - https://www.youtube.com/embed/VIDEO_ID
         *   - https://www.youtube.com/live/VIDEO_ID
         *   - https://www.youtube-nocookie.com/embed/VIDEO_ID
         *   - bare 11-character VIDEO_ID
         */
        fun extractVideoId(rawUrl: String): String? {
            val trimmed = rawUrl.trim()
            if (trimmed.isEmpty()) return null

            if (trimmed.matches(VIDEO_ID_REGEX)) return trimmed

            val candidate = if (trimmed.contains("://")) trimmed else "https://$trimmed"
            val url = runCatching { URL(candidate) }.getOrNull() ?: return null
            val host = url.host?.lowercase()?.removePrefix("www.")?.removePrefix("m.") ?: return null
            val path = url.path ?: ""

            val fromQuery: String? = if (host.endsWith("youtube.com") || host.endsWith("youtube-nocookie.com")) {
                queryParam(url.query, "v")
            } else null
            if (fromQuery != null && fromQuery.matches(VIDEO_ID_REGEX)) return fromQuery

            if (host == "youtu.be") {
                val id = path.trimStart('/').substringBefore('/')
                if (id.matches(VIDEO_ID_REGEX)) return id
            }

            if (host.endsWith("youtube.com") || host.endsWith("youtube-nocookie.com")) {
                val segments = path.trim('/').split('/')
                val segmentId = when (segments.firstOrNull()) {
                    "shorts", "embed", "live", "v" -> segments.getOrNull(1)
                    else -> null
                }
                if (segmentId != null && segmentId.matches(VIDEO_ID_REGEX)) return segmentId
            }

            return null
        }

        private val VIDEO_ID_REGEX = Regex("[A-Za-z0-9_-]{11}")

        private fun queryParam(query: String?, key: String): String? {
            if (query.isNullOrBlank()) return null
            for (part in query.split('&')) {
                val eq = part.indexOf('=')
                if (eq < 0) continue
                if (part.substring(0, eq) == key) {
                    return java.net.URLDecoder.decode(part.substring(eq + 1), "UTF-8")
                }
            }
            return null
        }

        internal fun normalizeTranscriptUrl(baseUrl: String): String {
            val trimmed = baseUrl.trim()
            if (trimmed.startsWith("http://") || trimmed.startsWith("https://")) {
                return trimmed
            }
            return if (trimmed.startsWith("/")) "$YOUTUBE_BASE_URL$trimmed" else "$YOUTUBE_BASE_URL/$trimmed"
        }
    }
}
