package com.niranjan.englisharticle.data

import android.util.Xml
import com.niranjan.englisharticle.domain.YouTubeTranscript
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONArray
import org.json.JSONObject
import org.xmlpull.v1.XmlPullParser
import java.io.BufferedReader
import java.io.InputStreamReader
import java.io.StringReader
import java.net.HttpURLConnection
import java.net.URL

/**
 * Fetches transcripts for public YouTube videos by scraping the watch page,
 * locating the caption tracks listed in `ytInitialPlayerResponse`, and
 * downloading the timed-text XML for the preferred track.
 */
class YouTubeTranscriptService {

    suspend fun fetchTranscript(rawUrl: String): YouTubeTranscript = withContext(Dispatchers.IO) {
        val videoId = extractVideoId(rawUrl)
            ?: error("Could not find a YouTube video ID in this link.")

        val watchHtml = httpGet("$WATCH_URL?v=$videoId&hl=en")
        val playerJson = extractPlayerResponseJson(watchHtml)
            ?: error("Could not read the YouTube watch page. Try opening the video in the YouTube app and sharing it.")

        val player = JSONObject(playerJson)
        val title = player
            .optJSONObject("videoDetails")
            ?.optString("title")
            ?.takeIf { it.isNotBlank() }
            .orEmpty()
        val author = player
            .optJSONObject("videoDetails")
            ?.optString("author")
            ?.takeIf { it.isNotBlank() }
            .orEmpty()

        val tracksJson = player
            .optJSONObject("captions")
            ?.optJSONObject("playerCaptionsTracklistRenderer")
            ?.optJSONArray("captionTracks")

        if (tracksJson == null || tracksJson.length() == 0) {
            error("This video does not have any captions or transcript available.")
        }

        val track = pickPreferredTrack(tracksJson)
            ?: error("This video does not have a transcript we can read.")

        val transcriptUrl = track.optString("baseUrl")
            .takeIf { it.isNotBlank() }
            ?: error("YouTube returned an empty transcript URL.")

        val transcriptXml = httpGet(transcriptUrl)
        val transcript = parseTranscriptXml(transcriptXml)
        if (transcript.isBlank()) {
            error("YouTube returned an empty transcript for this video.")
        }

        YouTubeTranscript(
            videoId = videoId,
            title = title,
            author = author,
            languageCode = track.optString("languageCode").takeIf { it.isNotBlank() }.orEmpty(),
            isAutoGenerated = track.optString("kind") == "asr",
            transcript = transcript
        )
    }

    private fun pickPreferredTrack(tracks: JSONArray): JSONObject? {
        val list = (0 until tracks.length()).map { tracks.getJSONObject(it) }
        val englishManual = list.firstOrNull {
            it.optString("languageCode").startsWith("en", ignoreCase = true) &&
                it.optString("kind") != "asr"
        }
        if (englishManual != null) return englishManual

        val englishAuto = list.firstOrNull {
            it.optString("languageCode").startsWith("en", ignoreCase = true)
        }
        if (englishAuto != null) return englishAuto

        return list.firstOrNull()
    }

    private fun httpGet(urlString: String): String {
        val connection = (URL(urlString).openConnection() as HttpURLConnection).apply {
            requestMethod = "GET"
            connectTimeout = 15_000
            readTimeout = 20_000
            instanceFollowRedirects = true
            setRequestProperty("User-Agent", USER_AGENT)
            setRequestProperty("Accept-Language", "en-US,en;q=0.9")
        }
        try {
            val code = connection.responseCode
            val stream = if (code in 200..299) connection.inputStream else connection.errorStream
            val body = stream?.let {
                BufferedReader(InputStreamReader(it, Charsets.UTF_8)).use { reader -> reader.readText() }
            }.orEmpty()
            if (code !in 200..299) {
                error("YouTube request failed (HTTP $code).")
            }
            return body
        } finally {
            connection.disconnect()
        }
    }

    private fun parseTranscriptXml(xml: String): String {
        val parser = Xml.newPullParser()
        parser.setFeature(XmlPullParser.FEATURE_PROCESS_NAMESPACES, false)
        parser.setInput(StringReader(xml))

        val builder = StringBuilder()
        var event = parser.eventType
        var inText = false
        while (event != XmlPullParser.END_DOCUMENT) {
            when (event) {
                XmlPullParser.START_TAG -> if (parser.name == "text") inText = true
                XmlPullParser.TEXT -> if (inText) {
                    val piece = decodeEntities(parser.text).trim()
                    if (piece.isNotEmpty()) {
                        if (builder.isNotEmpty()) builder.append(' ')
                        builder.append(piece)
                    }
                }
                XmlPullParser.END_TAG -> if (parser.name == "text") inText = false
            }
            event = parser.next()
        }
        return builder.toString()
    }

    /**
     * The transcript text is double-escaped: outer XML wraps content like
     * `&amp;#39;` which decodes to `&#39;` and then `'`.
     */
    private fun decodeEntities(text: String): String {
        var decoded = text
            .replace("&amp;", "&")
            .replace("&lt;", "<")
            .replace("&gt;", ">")
            .replace("&quot;", "\"")
            .replace("&apos;", "'")
        decoded = NUMERIC_ENTITY.replace(decoded) { match ->
            val raw = match.groupValues[1]
            val codePoint = if (raw.startsWith("x", ignoreCase = true)) {
                raw.drop(1).toIntOrNull(16)
            } else {
                raw.toIntOrNull()
            }
            codePoint?.let {
                runCatching { String(Character.toChars(it)) }.getOrNull()
            } ?: match.value
        }
        return decoded
    }

    companion object {
        private const val WATCH_URL = "https://www.youtube.com/watch"
        private const val USER_AGENT =
            "Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) " +
                "Chrome/124.0.0.0 Mobile Safari/537.36"
        private val NUMERIC_ENTITY = Regex("&#(x?[0-9A-Fa-f]+);")
        private val PLAYER_RESPONSE_PATTERNS = listOf(
            Regex("""var\s+ytInitialPlayerResponse\s*=\s*"""),
            Regex("""ytInitialPlayerResponse"\s*:\s*"""),
            Regex("""ytInitialPlayerResponse\s*=\s*""")
        )

        /**
         * Accepts the common YouTube link shapes:
         *   - https://www.youtube.com/watch?v=VIDEO_ID
         *   - https://m.youtube.com/watch?v=VIDEO_ID
         *   - https://youtu.be/VIDEO_ID
         *   - https://www.youtube.com/shorts/VIDEO_ID
         *   - https://www.youtube.com/embed/VIDEO_ID
         *   - https://www.youtube.com/live/VIDEO_ID
         *   - https://www.youtube-nocookie.com/embed/VIDEO_ID
         *   - bare 11-character VIDEO_ID
         */
        fun extractVideoId(rawUrl: String): String? {
            val trimmed = rawUrl.trim()
            if (trimmed.isEmpty()) return null

            if (trimmed.matches(VIDEO_ID_REGEX)) return trimmed

            val candidate = if (trimmed.contains("://")) trimmed else "https://$trimmed"
            val url = runCatching { URL(candidate) }.getOrNull() ?: return null
            val host = url.host?.lowercase()?.removePrefix("www.")?.removePrefix("m.") ?: return null
            val path = url.path ?: ""

            val fromQuery: String? = if (host.endsWith("youtube.com") || host.endsWith("youtube-nocookie.com")) {
                queryParam(url.query, "v")
            } else null
            if (fromQuery != null && fromQuery.matches(VIDEO_ID_REGEX)) return fromQuery

            if (host == "youtu.be") {
                val id = path.trimStart('/').substringBefore('/')
                if (id.matches(VIDEO_ID_REGEX)) return id
            }

            if (host.endsWith("youtube.com") || host.endsWith("youtube-nocookie.com")) {
                val segments = path.trim('/').split('/')
                val segmentId = when (segments.firstOrNull()) {
                    "shorts", "embed", "live", "v" -> segments.getOrNull(1)
                    else -> null
                }
                if (segmentId != null && segmentId.matches(VIDEO_ID_REGEX)) return segmentId
            }

            return null
        }

        private val VIDEO_ID_REGEX = Regex("[A-Za-z0-9_-]{11}")

        private fun queryParam(query: String?, key: String): String? {
            if (query.isNullOrBlank()) return null
            for (part in query.split('&')) {
                val eq = part.indexOf('=')
                if (eq < 0) continue
                if (part.substring(0, eq) == key) {
                    return java.net.URLDecoder.decode(part.substring(eq + 1), "UTF-8")
                }
            }
            return null
        }

        /**
         * Locates the JSON object passed to `ytInitialPlayerResponse` in the watch HTML
         * and returns it as a raw JSON string (curly-brace balanced).
         */
        fun extractPlayerResponseJson(html: String): String? {
            for (pattern in PLAYER_RESPONSE_PATTERNS) {
                val match = pattern.find(html) ?: continue
                val start = html.indexOf('{', match.range.last + 1)
                if (start < 0) continue
                val end = findMatchingBrace(html, start) ?: continue
                return html.substring(start, end + 1)
            }
            return null
        }

        private fun findMatchingBrace(text: String, openIndex: Int): Int? {
            var depth = 0
            var inString = false
            var escape = false
            var i = openIndex
            while (i < text.length) {
                val ch = text[i]
                if (inString) {
                    if (escape) {
                        escape = false
                    } else if (ch == '\\') {
                        escape = true
                    } else if (ch == '"') {
                        inString = false
                    }
                } else {
                    when (ch) {
                        '"' -> inString = true
                        '{' -> depth++
                        '}' -> {
                            depth--
                            if (depth == 0) return i
                        }
                    }
                }
                i++
            }
            return null
        }
    }
}
