package com.niranjan.englisharticle.domain

data class YouTubeTranscript(
    val videoId: String,
    val title: String,
    val author: String,
    val languageCode: String,
    val isAutoGenerated: Boolean,
    val transcript: String
)
